# docker-compose.yml
version: '3'
services:
  client:
    image: node:20-bullseye
    volumes:
      - ./client/client/:/client
    working_dir: /client
    entrypoint: yarn
    command: start
    ports:
      - "3000:3000"

  server:
    image: node:20-bullseye
    volumes:
      - ./server/:/server
    working_dir: /server
    entrypoint: npm
    environment:
      PORT: ${SERVER_PORT}
      POSTGRES_DB: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    command:
      - run
      - dev
    ports:
      - "3100:3000"

  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    command: "-c logging_collector=on"
