version: '3'
services:
  client:
    image: node:20-alpine3.17
    volumes:
      - ./client/:/client
    working_dir: /client
    entrypoint: yarn
    command: start

  express_server:
    image: node:20-alpine3.17
    volumes:
      - ./server/:/server
    working_dir: /server
    entrypoint: npm
    environment:
      PORT: ${SERVER_PORT}
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command:
      - run
      - dev

  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    command: "-c logging_collector=on"

  nginx:
    image: nginx:1.25.0-alpine
    volumes:
      - ./nginx/default.conf/:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
