name: Pipeline for build and test

on: [pull_request, push]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: |
        cd server
        npm install
    
    - name: Run tests
      run: npm test
